# Generated by Django 5.0 on 2024-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.CharField(choices=[('Espresso', 'Espresso'), ('Americano', 'Americano'), ('Latte', 'Latte'), ('Cappuccino', 'Cappuccino'), ('Flat White', 'Flat White'), ('Macchiato', 'Macchiato'), ('Mocha', 'Mocha'), ('Hot Chocolate', 'Hot Chocolate')], max_length=50)),
                ('shot', models.CharField(blank=True, choices=[('Single', 'Single Shot'), ('Double', 'Double Shot'), ('Triple', 'Triple Shot')], max_length=50, null=True)),
                ('milk', models.CharField(choices=[('Whole Milk', 'Whole Milk'), ('Semi-skimmed Milk', 'Semi-skimmed Milk'), ('Skimmed Milk', 'Skimmed Milk'), ('Almond Milk', 'Almond Milk'), ('Oat Milk', 'Oat Milk'), ('Cashew Milk', 'Cashew Milk'), ('Soya Milk', 'Soya Milk'), ('Goat Milk', 'Goat Milk'), ('Yak Milk', 'Yak Milk'), ('Nettle Milk', 'Nettle Milk'), ('Half and Half', 'Half and Half')], max_length=50)),
                ('milk_option1', models.CharField(blank=True, choices=[('Whole Milk', 'Whole Milk'), ('Semi-skimmed Milk', 'Semi-skimmed Milk'), ('Skimmed Milk', 'Skimmed Milk'), ('Almond Milk', 'Almond Milk'), ('Oat Milk', 'Oat Milk'), ('Cashew Milk', 'Cashew Milk'), ('Soya Milk', 'Soya Milk'), ('Goat Milk', 'Goat Milk'), ('Yak Milk', 'Yak Milk'), ('Nettle Milk', 'Nettle Milk'), ('Half and Half', 'Half and Half')], max_length=50, null=True)),
                ('milk_option2', models.CharField(blank=True, choices=[('Whole Milk', 'Whole Milk'), ('Semi-skimmed Milk', 'Semi-skimmed Milk'), ('Skimmed Milk', 'Skimmed Milk'), ('Almond Milk', 'Almond Milk'), ('Oat Milk', 'Oat Milk'), ('Cashew Milk', 'Cashew Milk'), ('Soya Milk', 'Soya Milk'), ('Goat Milk', 'Goat Milk'), ('Yak Milk', 'Yak Milk'), ('Nettle Milk', 'Nettle Milk'), ('Half and Half', 'Half and Half')], max_length=50, null=True)),
                ('flavours', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
