# Generated by Django 5.0 on 2025-01-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeorder',
            name='pastries',
            field=models.JSONField(default=list),
        ),
    ]
